server:
  port: 8080
spring:
  application:
    name: spring-boot-one-demo
#  redis:
#    cluster:
#      nodes: 192.168.1.222:7000,192.168.1.222:7001,192.168.1.222:7002,192.168.1.223:7003,192.168.1.223:7004,192.168.1.223:7005,192.168.1.224:7006,192.168.1.224:7007,192.168.1.224:7008
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/zlb-db-01?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password:
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  aop:
    proxy-target-class: true

# 配置mybatis的mapper文件地址
mybatis:
  mapper-locations: classpath:/mybatis/*.xml
#logging:
#  level:
#    root: debug
